generate grid
poprobertdaniel/KineticSass pull request #7
Opened 2017-09-11 12:01 UTC by ionuttoader

2017-09-11 12:53 UTC, robipop22 requested changes

2017-09-11 12:53 UTC, poprobertdaniel commented on root/src/style/_partials/variables.scss
> +$columns: ('col-', 'col-offset');
SCOATE BA LINIA, NIMIC NU STII FACE

2017-09-13 08:43 UTC, dianapintea submitted a review, later dismissed

2017-09-13 10:36 UTC, radufarcas10 approved these changes

2017-09-15 06:55 UTC, merged